services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis  # 1. Rediska bog'liqlikni qo'shdik

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=related
      - POSTGRES_PASSWORD=java7834

  # 2. Redis servisining o'zini qo'shdik
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: