# Generated by Django 6.0.4 on 2026-04-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_insurance_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
