# Generated by Django 6.0.4 on 2026-04-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_alter_insurance_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='car_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
