# Generated by Django 6.0.4 on 2026-04-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_alter_insurance_car_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='phone_number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
