# Generated by Django 6.0.4 on 2026-04-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_alter_insurance_expiry_date_alter_insurance_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
    ]
