# Generated by Django 5.2.15 on 2026-06-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_alter_insurance_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
