# Generated by Django 5.2.15 on 2026-06-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_alter_insurance_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insurance',
            new_name='InsuranceWay',
        ),
    ]
