# Generated by Django 5.2.15 on 2026-06-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_rename_insurance_insuranceway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceway',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
